# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            abbett.org
author:
  name:           Jonathan Abbett
  email:          jonathan@abbett.org
description:      "Web crafter. Lifelong Bay Stater. Amateur kosher cheesemaker."
baseurl:          ""
url:              "https://abbett.org"
twitter_username: jonabbett
github_username:  jabbett

# Build settings
markdown:         kramdown
permalink:        /:year/:month/:title/index:output_ext

# Assets
sass:
  sass_dir:       _sass
  style:          compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll/footnotes
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
